const mongoose = require("mongoose");

const tutorOfferSchema = new mongoose.Schema({
  userId: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
  educationLevels: {
    type: [String],
    enum: ["ESO", "Bachillerato", "FP", "Universidad", "Oposiciones", "Postgrado", "EBAU", "Idiomas"],
    required: true
  },
  subject: { type: String, required: true },
  description: { type: String },
  price: { type: Number, required: true },
  modality: { type: String, enum: ["Presencial", "Online", "Ambas"], default: "Online" },
  location: { type: String, enum: [ "A Coruña",
                                      "Albacete",
                                     "Alicante",
                                     "Almería",
                                     "Ávila",
                                     "Badajoz",
                                     "Barcelona",
                                     "Bilbao",
                                     "Burgos",
                                     "Cáceres",
                                     "Cádiz",
                                     "Castellón de la Plana",
                                     "Ceuta",
                                     "Ciudad Real",
                                     "Córdoba",
                                     "Cuenca",
                                     "Girona",
                                     "Granada",
                                     "Guadalajara",
                                     "Huelva",
                                     "Huesca",
                                     "Jaén",
                                     "Logroño",
                                     "Las Palmas de Gran Canaria",
                                     "León",
                                     "Lleida",
                                     "Lugo",
                                     "Madrid",
                                     "Málaga",
                                     "Melilla",
                                     "Murcia",
                                     "Ourense",
                                     "Oviedo",
                                     "Palencia",
                                     "Palma",
                                     "Pamplona",
                                     "Pontevedra",
                                     "Salamanca",
                                     "San Sebastián",
                                     "Santa Cruz de Tenerife",
                                     "Santander",
                                     "Segovia",
                                     "Sevilla",
                                     "Soria",
                                     "Tarragona",
                                     "Teruel",
                                     "Toledo",
                                     "Valencia",
                                     "Valladolid",
                                     "Vigo",
                                     "Vitoria-Gasteiz",
                                     "Zamora",
                                     "Zaragoza"], default: "Madrid" },
  createdAt: { type: Date, default: Date.now }
});

module.exports = mongoose.model("TutorOffer", tutorOfferSchema);
